---
- name: Deploy Database for Wordpress
  hosts: database
  become: true
  vars:
    ansible_become_pass: 'vagrant' #sudoのパスが必要な場合
  environment:
    http_proxy: "http://proxy.example.local:8080" #インターネットへのプロキシが必要な場合
    https_proxy: "http://proxy.example.local:8080"
  roles:
    - { role: common, tags: common } #OSの基本設定
    - { role: maridb, tags: mariadb } #DBの構築
    #DB接続用ロードバランサの構築
    - { role: proxy, cluster_service: db_cluster, tags: haproxy }
    - { role: keepalived, cluster_service: db_cluster, tags: keepalived }

- name: Deploy Application for Wordpress
  hosts: apps
  become: true
  roles:
    - { role: common, tags: common } #OSの基本設定
    - { role: nginx, tags: nginx } #PHP実行敢行の構築
    - { role: php-fpm, tags: php-fpm } 
    - { role: wordpress, tags: wordpress } #WPの展開

- name: Deploy Application for Wordpress
  hosts: lbs
  become: true
  roles:
    - { roles: common, tags: common } #OSの基本設定
    #アプリケーション専用のロードバランサの構築
    - { roles: haproxy, cluster_service: app_cluster, tags: haproxy }
    - { roles: keepalived, cluster_srvice: app_cluster, tags: keepaliveds }

